name: EssentialsPayLogger
main: com.radthorne.EssentialsPayLogger.EssentialsPayLogger
version: 1.0
author: kukelekuuk00
depend: [Essentials]

commands:
    pay:
        description: Pays another player from your balance
        usage: /<command> <player> <amount>
        aliases: [lpay, logpay]
    transactions:
        description: Shows a list of recent transactions
        usage: /<command> [page|player] [page]
        aliases: [ltransactions, trans, ltrans, logtrans, logtransactions]
permissions:
    essentialspaylogger.pay:
        description: Gives access to the /pay command.
    essentialspaylogger.transactions:
        description: Gives access to the /transactions command.
    essentialspaylogger.transactions.others:
        description: Gives access to the /transactions <username> command.
